#
# Makefile -- build components for book cover
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
tunnel-1.pdf:	tunnel.mp
	TEX=latex mpost tunnel.mp
	mptopdf tunnel.1
	mptopdf tunnel.2
	mptopdf tunnel.3
