#
# Makefile -- build the instructions
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
all:	zuteilung.pdf

zuteilung.pdf:	zuteilung.tex
	pdflatex zuteilung.tex

seminararbeit.pdf:	seminararbeit.tex aufgaben.tex
	pdflatex seminararbeit.tex

praesentation.pdf:	praesentation.tex
	pdflatex praesentation.tex
